# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pSgXj2ZnBtUCxj3xGw8qVFztpcsR5AC

# APL Logistics: Profitability Performance Analysis
**Project Lead:** Adarsh | **Department:** AIML Engineering  
**Focus:** Transforming Operational Logistics into Financial Intelligence

---

### **Phase 1: Foundation – Data Integrity & Audit**

**Business Objective:**
Before deriving strategic insights, we must ensure our data is reliable. In this phase, we transform raw, fragmented logistics data into a "Golden Version" that serves as the single source of truth for all subsequent profit-intelligence models.

**Strategic Implementation Pillars:**
*   **Standardization:** Implementing uniform naming conventions (snake_case) to ensure our code remains consistent and readable across all phases.
*   **Financial Validation:** Scrubbing core financial pillars—*Sales* and *Profit*—by removing currency symbols and data-entry errors, ensuring every calculation is mathematically sound.
*   **Data Integrity Audit:** Identifying and removing duplicate records and handling missing information to guarantee our analysis is based on high-fidelity, trusted data.
*   **Operational Readiness:** Creating a validated asset (`APL_Logistics_Cleaned.csv`) optimized for immediate use in our diagnostic and predictive strategy modules.

**Strategic Impact:**
This is a critical audit that transforms raw, messy data into an **actionable business asset**. A robust foundation here guarantees that our future dashboards are based on verified, professional-grade intelligence.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

uploaded_files = files.upload()
file_path = next(iter(uploaded_files))

try:
    df = pd.read_csv(file_path, low_memory=False)
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding="latin1", low_memory=False)

df.columns = (
    df.columns.str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

profit_column = next(
    (column for column in ["order_profit_per_order", "profit"] if column in df.columns),
    None
)

if "sales" not in df.columns or profit_column is None:
    raise KeyError("The uploaded file must contain Sales and Order Profit Per Order columns.")

df.rename(columns={profit_column: "profit"}, inplace=True)

for column in ["sales", "profit"]:
    df[column] = pd.to_numeric(
        df[column].astype(str).str.replace(r"[$,]", "", regex=True),
        errors="coerce"
    )

df = df.drop_duplicates()
df = df.dropna(subset=["sales", "profit"])
df = df[df["sales"] > 0].copy()

text_columns = df.select_dtypes(include="object").columns
df[text_columns] = df[text_columns].replace(r"^\s*$", np.nan, regex=True).fillna("Unknown")

df.reset_index(drop=True, inplace=True)
df.to_csv("APL_Logistics_Cleaned.csv", index=False)

print("Cleaned dataset size:", df.shape)
print("Saved file: APL_Logistics_Cleaned.csv")

"""### Phase 2: Diagnostic Insight – Profitability & Market Intelligence

#### 1. Business Objective
With a cleaned dataset established, we pivot to the Diagnostic Phase. Our goal here is to move beyond simple revenue figures to understand the true financial health of APL Logistics by mapping costs against revenue at a granular market level.

#### 2. Strategic Implementation Pillars

* **Margin Intelligence:** Calculating the estimated_cost and profit_margin for every transaction to expose exactly how much value is being captured vs. lost.

* **Performance Benchmarking:** Aggregating data by market to identify which regions are the primary drivers of profit and which are operating at a deficit.

* **Visual Transparency:** Utilizing comparative bar charts to present the overall financial position, allowing stakeholders to identify high-value vs. loss-making segments at a glance.

* **Actionable Intelligence:** Generating validated summary files that serve as the foundational dataset for our upcoming optimization simulations.

#### 3. Strategic Impact
This phase shifts the project from data preparation to Strategic Analysis. By isolating loss-making orders and regional profit drivers, we create a roadmap for tactical interventions, ensuring the business can optimize for profitability rather than just volume.
"""

df["estimated_cost"] = df["sales"] - df["profit"]
df["profit_margin"] = np.where(
    df["sales"] > 0,
    df["profit"] / df["sales"] * 100,
    np.nan
)

total_sales = df["sales"].sum()
total_profit = df["profit"].sum()
total_cost = df["estimated_cost"].sum()
profit_margin = total_profit / total_sales * 100
loss_making_orders = (df["profit"] < 0).sum()

financial_overview = pd.DataFrame(
    {
        "Metric": [
            "Total Sales",
            "Estimated Cost",
            "Total Profit",
            "Overall Profit Margin (%)",
            "Loss-Making Orders"
        ],
        "Value": [
            total_sales,
            total_cost,
            total_profit,
            profit_margin,
            loss_making_orders
        ]
    }
)

market_summary = (
    df.groupby("market", as_index=False)
    .agg(
        total_sales=("sales", "sum"),
        total_profit=("profit", "sum"),
        estimated_cost=("estimated_cost", "sum"),
        order_count=("sales", "size")
    )
)

market_summary["profit_margin"] = (
    market_summary["total_profit"] / market_summary["total_sales"] * 100
)

market_summary = market_summary.sort_values("total_profit", ascending=False)

top_markets = (
    market_summary.nlargest(10, "total_sales")
    .sort_values("total_sales")
)

display(financial_overview)
display(market_summary)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

axes[0].bar(
    ["Sales", "Estimated Cost", "Profit"],
    [total_sales, total_cost, total_profit],
    color=["#4C78A8", "#F58518", "#54A24B"]
)
axes[0].set_title("Overall Financial Position")
axes[0].set_ylabel("Amount")

axes[1].barh(
    top_markets["market"],
    top_markets["total_profit"],
    color=np.where(top_markets["total_profit"] >= 0, "#54A24B", "#E45756")
)
axes[1].set_title("Profit by Top Sales Markets")
axes[1].set_xlabel("Profit")

plt.tight_layout()
plt.show()

financial_overview.to_csv("/content/Phase_2_Financial_Overview.csv", index=False)
market_summary.to_csv("/content/Phase_2_Market_Performance.csv", index=False)

"""### Phase 3: Category & Product Performance Optimization

#### 1. Business Objective
In this phase, we drill down from market-level trends to product-level performance. We are applying granular diagnostics to identify which specific categories and products are fueling our growth and, more importantly, which high-revenue items are suffering from low-margin performance.

#### 2. Strategic Implementation Pillars

* **Category Analysis:** Evaluating performance across product categories to pinpoint segments contributing significantly to total profit versus those operating at a loss.

* **High-Revenue/Low-Margin Identification:** Using quantile-based analysis to flag top-selling products that fail to meet our overall profit margin threshold—the "silent killers" of profitability.

* **Product Profitability Benchmarking:** Identifying the top 10 most profitable products to create a success template for future inventory and marketing decisions.

* **Actionable Intelligence:** Exporting validated performance datasets (`Category_Performance.csv`, `Product_Performance.csv`, and `High_Revenue_Low_Margin_Products.csv`) to facilitate targeted operational strategy.

#### 3. Strategic Impact
This phase represents the shift from high-level observation to tactical precision. By isolating items that drive revenue but destroy margins, we provide leadership with the empirical evidence required to prune underperforming products, optimize pricing models, and maximize the return on every unit sold.
"""

if "estimated_cost" not in df.columns:
    df["estimated_cost"] = df["sales"] - df["profit"]

overall_profit_margin = df["profit"].sum() / df["sales"].sum() * 100

category_summary = (
    df.groupby("category_name", as_index=False)
    .agg(
        total_sales=("sales", "sum"),
        total_profit=("profit", "sum"),
        estimated_cost=("estimated_cost", "sum"),
        order_count=("sales", "size"),
        loss_making_orders=("profit", lambda values: (values < 0).sum())
    )
)

category_summary["profit_margin"] = (
    category_summary["total_profit"] / category_summary["total_sales"] * 100
)

category_summary = category_summary.sort_values("total_profit", ascending=False)

product_summary = (
    df.groupby(["category_name", "product_name"], as_index=False)
    .agg(
        total_sales=("sales", "sum"),
        total_profit=("profit", "sum"),
        estimated_cost=("estimated_cost", "sum"),
        order_count=("sales", "size"),
        loss_making_orders=("profit", lambda values: (values < 0).sum())
    )
)

product_summary["profit_margin"] = (
    product_summary["total_profit"] / product_summary["total_sales"] * 100
)

product_summary = product_summary.sort_values("total_profit", ascending=False)

high_sales_cutoff = product_summary["total_sales"].quantile(0.75)

high_revenue_low_margin = (
    product_summary[
        (product_summary["total_sales"] >= high_sales_cutoff) &
        (product_summary["profit_margin"] < overall_profit_margin)
    ]
    .sort_values("total_sales", ascending=False)
)

loss_making_categories = (
    category_summary[category_summary["total_profit"] < 0]
    .sort_values("total_profit")
)

display(category_summary)
display(product_summary.head(10))
display(high_revenue_low_margin)
display(loss_making_categories)

top_categories = (
    category_summary.nlargest(10, "total_sales")
    .sort_values("total_sales")
)

top_products = (
    product_summary.nlargest(10, "total_profit")
    .sort_values("total_profit")
)

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

axes[0].barh(
    top_categories["category_name"],
    top_categories["total_sales"],
    color="#4C78A8"
)
axes[0].set_title("Top Categories by Sales")
axes[0].set_xlabel("Total Sales")

axes[1].barh(
    top_products["product_name"],
    top_products["total_profit"],
    color=np.where(top_products["total_profit"] >= 0, "#54A24B", "#E45756")
)
axes[1].set_title("Top Products by Profit")
axes[1].set_xlabel("Total Profit")

plt.tight_layout()
plt.show()

category_summary.to_csv("/content/Phase_3_Category_Performance.csv", index=False)
product_summary.to_csv("/content/Phase_3_Product_Performance.csv", index=False)
high_revenue_low_margin.to_csv("/content/Phase_3_High_Revenue_Low_Margin_Products.csv", index=False)

"""### Phase 4: Strategic Customer Segmentation & Regional Profitability

#### 1. Business Objective
In this final diagnostic phase, we transition from product-level analysis to high-level strategic intelligence. By evaluating customer lifetime value and regional performance, we identify who our "Strategic" partners are and how discount strategies impact our bottom line.

#### 2. Strategic Implementation Pillars

* **Customer Value Index (CVI):** We have engineered a weighted scoring system (50% Profit, 30% Sales, 20% Margin) to rank customers and categorize them into tiers, from 'Low Value' to 'Strategic.'

* **Discount Band Analysis:** We are testing the correlation between discount rates and profitability. This identifies whether our current discounting strategies are driving volume at the expense of margin.

* **Regional Operational Heatmap:** We are mapping performance across global regions, providing a high-level view of where APL Logistics is currently capturing the most significant value.

* **Actionable Intelligence:** This phase creates the final strategic roadmap, enabling leadership to prioritize 'Strategic' customers and re-evaluate discount policies that may be eroding net profit.

#### 3. Strategic Impact
This phase completes the transformation of raw logistics data into a **Strategic Decision Support System**. We have successfully shifted the narrative from "operational tracking" to "profit-led growth," providing the necessary insights to build an AI-driven predictive model for future customer loyalty and margin preservation.
"""

df["profit_margin"] = np.where(
    df["sales"] > 0,
    df["profit"] / df["sales"] * 100,
    np.nan
)

customer_summary = (
    df.groupby(["customer_id", "customer_segment"], as_index=False)
    .agg(
        total_sales=("sales", "sum"),
        total_profit=("profit", "sum"),
        order_count=("sales", "size")
    )
)

customer_summary["profit_margin"] = (
    customer_summary["total_profit"] / customer_summary["total_sales"] * 100
)

customer_summary["profit_score"] = customer_summary["total_profit"].rank(pct=True) * 100
customer_summary["sales_score"] = customer_summary["total_sales"].rank(pct=True) * 100
customer_summary["margin_score"] = customer_summary["profit_margin"].rank(pct=True) * 100

customer_summary["customer_value_index"] = (
    customer_summary["profit_score"] * 0.50 +
    customer_summary["sales_score"] * 0.30 +
    customer_summary["margin_score"] * 0.20
)

tier_labels = ["Low Value", "Developing", "High Value", "Strategic"]

customer_summary["value_tier"] = pd.qcut(
    customer_summary["customer_value_index"].rank(method="first"),
    q=4,
    labels=tier_labels
)

customer_summary = customer_summary.sort_values(
    "customer_value_index",
    ascending=False
)

top_customers = (
    customer_summary.nlargest(10, "total_profit")
    .sort_values("total_profit")
)

loss_making_customers = (
    customer_summary[customer_summary["total_profit"] < 0]
    .sort_values("total_profit")
    .head(10)
)

df["discount_rate"] = pd.to_numeric(
    df["order_item_discount_rate"],
    errors="coerce"
).fillna(0)

if df["discount_rate"].max() > 1:
    df["discount_rate"] = df["discount_rate"] / 100

discount_labels = ["No Discount", "1-5%", "6-10%", "11-20%", "Above 20%"]

df["discount_band"] = pd.cut(
    df["discount_rate"],
    bins=[-0.01, 0, 0.05, 0.10, 0.20, np.inf],
    labels=discount_labels
)

discount_summary = (
    df.groupby("discount_band", observed=False, as_index=False)
    .agg(
        total_sales=("sales", "sum"),
        total_profit=("profit", "sum"),
        order_count=("sales", "size")
    )
)

discount_summary["profit_margin"] = (
    discount_summary["total_profit"] / discount_summary["total_sales"] * 100
)

region_summary = (
    df.groupby(["market", "order_region"], as_index=False)
    .agg(
        total_sales=("sales", "sum"),
        total_profit=("profit", "sum"),
        order_count=("sales", "size")
    )
)

region_summary["profit_margin"] = (
    region_summary["total_profit"] / region_summary["total_sales"] * 100
)

region_summary = region_summary.sort_values("total_profit", ascending=False)

top_regions = (
    region_summary.nlargest(10, "total_profit")
    .sort_values("total_profit")
)

display(top_customers)
display(loss_making_customers)
display(discount_summary)
display(region_summary.head(10))

fig, axes = plt.subplots(1, 3, figsize=(22, 7))

axes[0].barh(
    top_customers["customer_id"].astype(str),
    top_customers["total_profit"],
    color="#54A24B"
)
axes[0].set_title("Top Customers by Profit")
axes[0].set_xlabel("Total Profit")

axes[1].bar(
    discount_summary["discount_band"].astype(str),
    discount_summary["profit_margin"],
    color="#F58518"
)
axes[1].set_title("Profit Margin by Discount Level")
axes[1].set_ylabel("Profit Margin (%)")
axes[1].tick_params(axis="x", rotation=30)

axes[2].barh(
    top_regions["order_region"],
    top_regions["total_profit"],
    color="#4C78A8"
)
axes[2].set_title("Top Regions by Profit")
axes[2].set_xlabel("Total Profit")

plt.tight_layout()
plt.show()

customer_summary.to_csv("/content/Phase_4_Customer_Value.csv", index=False)
discount_summary.to_csv("/content/Phase_4_Discount_Impact.csv", index=False)
region_summary.to_csv("/content/Phase_4_Regional_Performance.csv", index=False)

total_sales = df["sales"].sum()
total_profit = df["profit"].sum()
overall_margin = total_profit / total_sales * 100

best_category = category_summary.loc[category_summary["total_profit"].idxmax()]
lowest_category = category_summary.loc[category_summary["total_profit"].idxmin()]
best_customer = customer_summary.loc[customer_summary["total_profit"].idxmax()]
best_region = region_summary.loc[region_summary["total_profit"].idxmax()]

valid_discount_summary = discount_summary.dropna(subset=["profit_margin"])
weakest_discount_band = valid_discount_summary.loc[
    valid_discount_summary["profit_margin"].idxmin()
]

strategic_customers = (
    customer_summary["value_tier"]
    .astype(str)
    .eq("Strategic")
    .sum()
)

executive_summary = pd.DataFrame(
    {
        "Business Area": [
            "Total Sales",
            "Total Profit",
            "Overall Profit Margin",
            "Best Performing Category",
            "Lowest Performing Category",
            "Most Profitable Customer",
            "Most Profitable Region",
            "Lowest Margin Discount Band",
            "Strategic Customers"
        ],
        "Result": [
            f"${total_sales:,.2f}",
            f"${total_profit:,.2f}",
            f"{overall_margin:.2f}%",
            f"{best_category['category_name']} (${best_category['total_profit']:,.2f} profit)",
            f"{lowest_category['category_name']} (${lowest_category['total_profit']:,.2f} profit)",
            f"Customer {best_customer['customer_id']} (${best_customer['total_profit']:,.2f} profit)",
            f"{best_region['order_region']} (${best_region['total_profit']:,.2f} profit)",
            f"{weakest_discount_band['discount_band']} ({weakest_discount_band['profit_margin']:.2f}% margin)",
            strategic_customers
        ]
    }
)

display(executive_summary)

executive_summary.to_csv("/content/APL_Logistics_Executive_Summary.csv", index=False)

print(f"APL Logistics generated ${total_sales:,.2f} in sales and retained ${total_profit:,.2f} as profit.")
print(f"The overall profit margin is {overall_margin:.2f}%.")
print(f"The strongest category is {best_category['category_name']}.")
print(f"The strongest region is {best_region['order_region']}.")
print(f"The discount band with the weakest margin is {weakest_discount_band['discount_band']}.")
print("Saved file: /content/APL_Logistics_Executive_Summary.csv")